name: agenda_per_anna
description: Agenda personale multipiattaforma per Anna.
publish_to: "none"
version: 0.14.0+14

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  flutter_local_notifications: ^22.3.1
  flutter_timezone: ^5.1.0
  timezone: ^0.11.1
  file_picker: ^13.1.0
  local_auth: ^3.0.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#F7C8D7"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  remove_alpha_ios: true
