part of '../main.dart';

const Map<String, Map<String, String>> _d3Catalog = {
  "onboardingTitle": <String, String>{"en": "Your agenda, truly yours.", "it": "La tua agenda, davvero tua.", "es": "Tu agenda, de verdad tuya.", "fr": "Ton agenda, vraiment à toi.", "pt": "A tua agenda, verdadeiramente tua."},
  "onboardingDescription": <String, String>{"en": "Appointments, diary, habits, ideas and memories in one place. The app saves on your device first; connect an account only if you want sync and Noi ♡.", "it": "Appuntamenti, diario, abitudini, idee e ricordi in un unico posto. L’app salva prima sul dispositivo; collega un account solo se vuoi sincronizzazione e Noi ♡.", "es": "Citas, diario, hábitos, ideas y recuerdos en un solo lugar. La app guarda primero en el dispositivo; conecta una cuenta solo si quieres sincronización y Noi ♡.", "fr": "Rendez-vous, journal, habitudes, idées et souvenirs au même endroit. L’app enregistre d’abord sur l’appareil ; connecte un compte seulement si tu veux la synchronisation et Noi ♡.", "pt": "Compromissos, diário, hábitos, ideias e memórias num só lugar. A app guarda primeiro no dispositivo; liga uma conta apenas se quiseres sincronização e Noi ♡."},
  "quickCapture": <String, String>{"en": "Quick capture", "it": "Cattura veloce", "es": "Captura rápida", "fr": "Capture rapide", "pt": "Captura rápida"},
  "quickCaptureSubtitle": <String, String>{"en": "Add a thought or commitment in seconds.", "it": "Aggiungi un pensiero o un impegno in pochi secondi.", "es": "Añade una idea o un compromiso en segundos.", "fr": "Ajoute une pensée ou un engagement en quelques secondes.", "pt": "Adiciona um pensamento ou compromisso em segundos."},
  "personalDiary": <String, String>{"en": "Personal diary", "it": "Diario personale", "es": "Diario personal", "fr": "Journal personnel", "pt": "Diário pessoal"},
  "privateOrNoi": <String, String>{"en": "Private or Noi ♡", "it": "Privato o Noi ♡", "es": "Privado o Noi ♡", "fr": "Privé ou Noi ♡", "pt": "Privado ou Noi ♡"},
  "privateDefault": <String, String>{"en": "Private is always the default; share only what you explicitly choose.", "it": "Privato è sempre il default; condividi solo ciò che scegli esplicitamente.", "es": "Privado es siempre la opción predeterminada; comparte solo lo que elijas explícitamente.", "fr": "Privé reste toujours le choix par défaut ; partage uniquement ce que tu choisis explicitement.", "pt": "Privado é sempre a predefinição; partilha apenas o que escolheres explicitamente."},
  "optionalPrivacy": <String, String>{"en": "Optional privacy", "it": "Privacy opzionale", "es": "Privacidad opcional", "fr": "Confidentialité facultative", "pt": "Privacidade opcional"},
  "optionalPrivacySubtitle": <String, String>{"en": "PIN and biometrics if you want to protect the agenda.", "it": "PIN e biometria se vuoi proteggere l’agenda.", "es": "PIN y biometría si quieres proteger la agenda.", "fr": "PIN et biométrie si tu veux protéger l’agenda.", "pt": "PIN e biometria se quiseres proteger a agenda."},
  "start": <String, String>{"en": "Start", "it": "Inizia", "es": "Empezar", "fr": "Commencer", "pt": "Começar"},
  "passwordUpdated": <String, String>{"en": "Password updated. Your account is ready.", "it": "Password aggiornata. Il tuo account è pronto.", "es": "Contraseña actualizada. Tu cuenta está lista.", "fr": "Mot de passe mis à jour. Ton compte est prêt.", "pt": "Palavra-passe atualizada. A tua conta está pronta."},
  "chooseNewPassword": <String, String>{"en": "Choose a new password", "it": "Scegli una nuova password", "es": "Elige una nueva contraseña", "fr": "Choisis un nouveau mot de passe", "pt": "Escolhe uma nova palavra-passe"},
  "recoveryLinkValid": <String, String>{"en": "The recovery link is valid. Set a new password to complete account recovery.", "it": "Il link di recupero è valido. Imposta la nuova password per completare il recupero dell’account.", "es": "El enlace de recuperación es válido. Define una nueva contraseña para completar la recuperación de la cuenta.", "fr": "Le lien de récupération est valide. Définis un nouveau mot de passe pour terminer la récupération du compte.", "pt": "A ligação de recuperação é válida. Define uma nova palavra-passe para concluir a recuperação da conta."},
  "newPassword": <String, String>{"en": "New password", "it": "Nuova password", "es": "Nueva contraseña", "fr": "Nouveau mot de passe", "pt": "Nova palavra-passe"},
  "repeatPassword": <String, String>{"en": "Repeat password", "it": "Ripeti password", "es": "Repite la contraseña", "fr": "Répète le mot de passe", "pt": "Repete a palavra-passe"},
  "updatePassword": <String, String>{"en": "Update password", "it": "Aggiorna password", "es": "Actualizar contraseña", "fr": "Mettre à jour le mot de passe", "pt": "Atualizar palavra-passe"},
  "unlockAnna": <String, String>{"en": "Unlock Anna's Diary", "it": "Sblocca Anna's Diary", "es": "Desbloquear Anna's Diary", "fr": "Déverrouiller Anna's Diary", "pt": "Desbloquear Anna's Diary"},
  "incorrectPin": <String, String>{"en": "Incorrect PIN.", "it": "PIN non corretto.", "es": "PIN incorrecto.", "fr": "PIN incorrect.", "pt": "PIN incorreto."},
  "agendaLocked": <String, String>{"en": "Agenda locked", "it": "Agenda bloccata", "es": "Agenda bloqueada", "fr": "Agenda verrouillé", "pt": "Agenda bloqueada"},
  "unlock": <String, String>{"en": "Unlock", "it": "Sblocca", "es": "Desbloquear", "fr": "Déverrouiller", "pt": "Desbloquear"},
  "useBiometric": <String, String>{"en": "Use biometrics", "it": "Usa biometria", "es": "Usar biometría", "fr": "Utiliser la biométrie", "pt": "Usar biometria"},
  "retry": <String, String>{"en": "Retry", "it": "Riprova", "es": "Reintentar", "fr": "Réessayer", "pt": "Tentar novamente"},
  "identityIntro": <String, String>{"en": "One account for agenda, backup, sync and Noi ♡.", "it": "Un solo account per agenda, backup, sincronizzazione e Noi ♡.", "es": "Una sola cuenta para agenda, copia, sincronización y Noi ♡.", "fr": "Un seul compte pour agenda, sauvegarde, synchronisation et Noi ♡.", "pt": "Uma só conta para agenda, backup, sincronização e Noi ♡."},
  "haveEmailAccount": <String, String>{"en": "I already have an email/password account", "it": "Ho già un account email/password", "es": "Ya tengo una cuenta de email/contraseña", "fr": "J’ai déjà un compte e-mail/mot de passe", "pt": "Já tenho uma conta de email/palavra-passe"},
  "identityPrivacy": <String, String>{"en": "The account identifies only you. Private content stays separate from Noi ♡ and offline changes sync automatically when the network returns.", "it": "L’account identifica solo te. I contenuti privati restano separati da Noi ♡ e le modifiche offline vengono sincronizzate automaticamente quando torna la rete.", "es": "La cuenta solo te identifica a ti. El contenido privado permanece separado de Noi ♡ y los cambios sin conexión se sincronizan automáticamente cuando vuelve la red.", "fr": "Le compte ne sert qu’à t’identifier. Le contenu privé reste séparé de Noi ♡ et les modifications hors ligne se synchronisent automatiquement au retour du réseau.", "pt": "A conta identifica apenas a ti. Os conteúdos privados permanecem separados de Noi ♡ e as alterações offline sincronizam automaticamente quando a rede regressa."},
  "accountConnectedSyncPending": <String, String>{"en": "Account connected, sync still to complete", "it": "Account connesso, sincronizzazione da completare", "es": "Cuenta conectada, sincronización pendiente", "fr": "Compte connecté, synchronisation à terminer", "pt": "Conta ligada, sincronização por concluir"},
  "preparingSpace": <String, String>{"en": "Preparing your space…", "it": "Preparazione del tuo spazio…", "es": "Preparando tu espacio…", "fr": "Préparation de ton espace…", "pt": "A preparar o teu espaço…"},
  "cloudDisabled": <String, String>{"en": "Cloud not configured", "it": "Cloud non configurato", "es": "Nube no configurada", "fr": "Cloud non configuré", "pt": "Cloud não configurada"},
  "cloudConnecting": <String, String>{"en": "Connecting...", "it": "Connessione...", "es": "Conectando...", "fr": "Connexion...", "pt": "A ligar..."},
  "cloudSignedOut": <String, String>{"en": "Not connected", "it": "Non connesso", "es": "No conectado", "fr": "Non connecté", "pt": "Não ligado"},
  "cloudSyncing": <String, String>{"en": "Syncing...", "it": "Sincronizzazione...", "es": "Sincronizando...", "fr": "Synchronisation...", "pt": "A sincronizar..."},
  "cloudSyncError": <String, String>{"en": "Sync error", "it": "Errore di sincronizzazione", "es": "Error de sincronización", "fr": "Erreur de synchronisation", "pt": "Erro de sincronização"},
  "resetEmailSent": <String, String>{"en": "If the address is registered, you will receive an email to choose a new password.", "it": "Se l’indirizzo è registrato, riceverai una mail per scegliere una nuova password.", "es": "Si la dirección está registrada, recibirás un correo para elegir una nueva contraseña.", "fr": "Si l’adresse est enregistrée, tu recevras un e-mail pour choisir un nouveau mot de passe.", "pt": "Se o endereço estiver registado, receberás um email para escolher uma nova palavra-passe."},
  "agendaSynced": <String, String>{"en": "Agenda fully synced.", "it": "Agenda completamente sincronizzata.", "es": "Agenda completamente sincronizada.", "fr": "Agenda entièrement synchronisé.", "pt": "Agenda totalmente sincronizada."},
  "accountAndSync": <String, String>{"en": "Account and sync", "it": "Account e sincronizzazione", "es": "Cuenta y sincronización", "fr": "Compte et synchronisation", "pt": "Conta e sincronização"},
  "continueGoogle": <String, String>{"en": "Continue with Google", "it": "Continua con Google", "es": "Continuar con Google", "fr": "Continuer avec Google", "pt": "Continuar com Google"},
  "existingAccount": <String, String>{"en": "Sign in with an existing account", "it": "Accedi con account esistente", "es": "Iniciar sesión con una cuenta existente", "fr": "Se connecter avec un compte existant", "pt": "Iniciar sessão com uma conta existente"},
  "forgotPassword": <String, String>{"en": "Forgot password?", "it": "Password dimenticata?", "es": "¿Olvidaste la contraseña?", "fr": "Mot de passe oublié ?", "pt": "Esqueceste a palavra-passe?"},
  "noCompletedSync": <String, String>{"en": "No completed sync yet", "it": "Nessuna sincronizzazione completata", "es": "Aún no hay sincronizaciones completadas", "fr": "Aucune synchronisation terminée", "pt": "Ainda não há sincronizações concluídas"},
  "pendingChanges": <String, String>{"en": "Pending changes", "it": "Modifiche in attesa", "es": "Cambios pendientes", "fr": "Modifications en attente", "pt": "Alterações pendentes"},
  "syncNow": <String, String>{"en": "Sync now", "it": "Sincronizza ora", "es": "Sincronizar ahora", "fr": "Synchroniser maintenant", "pt": "Sincronizar agora"},
  "disconnectAccount": <String, String>{"en": "Disconnect account", "it": "Disconnetti account", "es": "Desconectar cuenta", "fr": "Déconnecter le compte", "pt": "Desligar conta"},
  "deleteAccountTitle": <String, String>{"en": "Permanently delete the account?", "it": "Eliminare definitivamente l’account?", "es": "¿Eliminar definitivamente la cuenta?", "fr": "Supprimer définitivement le compte ?", "pt": "Eliminar permanentemente a conta?"},
  "deleteAccountData": <String, String>{"en": "Delete account and data", "it": "Elimina account e dati", "es": "Eliminar cuenta y datos", "fr": "Supprimer le compte et les données", "pt": "Eliminar conta e dados"},
  "confirmation": <String, String>{"en": "Confirmation", "it": "Conferma", "es": "Confirmación", "fr": "Confirmation", "pt": "Confirmação"},
  "personalDiarySubtitle": <String, String>{"en": "Mood, good things and daily habits.", "it": "Mood, cose belle e abitudini quotidiane.", "es": "Estado de ánimo, cosas buenas y hábitos diarios.", "fr": "Humeur, belles choses et habitudes quotidiennes.", "pt": "Humor, coisas boas e hábitos diários."},
  "passwordMin8": <String, String>{"en": "Use at least 8 characters.", "it": "Usa almeno 8 caratteri.", "es": "Usa al menos 8 caracteres.", "fr": "Utilise au moins 8 caractères.", "pt": "Usa pelo menos 8 caracteres."},
  "passwordMismatch": <String, String>{"en": "The two passwords do not match.", "it": "Le due password non coincidono.", "es": "Las dos contraseñas no coinciden.", "fr": "Les deux mots de passe ne correspondent pas.", "pt": "As duas palavras-passe não coincidem."},
  "passwordUpdateFailed": <String, String>{"en": "Could not update the password. Try again.", "it": "Non è stato possibile aggiornare la password. Riprova.", "es": "No se pudo actualizar la contraseña. Inténtalo de nuevo.", "fr": "Impossible de mettre à jour le mot de passe. Réessaie.", "pt": "Não foi possível atualizar a palavra-passe. Tenta novamente."},
  "enterPin": <String, String>{"en": "Enter the PIN to continue.", "it": "Inserisci il PIN per continuare.", "es": "Introduce el PIN para continuar.", "fr": "Saisis le PIN pour continuer.", "pt": "Introduz o PIN para continuar."},
  "verifying": <String, String>{"en": "Verifying...", "it": "Verifica in corso...", "es": "Verificando...", "fr": "Vérification...", "pt": "A verificar..."},
  "accountInitFailed": <String, String>{"en": "Could not initialize the account.", "it": "Non riesco a inizializzare l’account.", "es": "No se pudo inicializar la cuenta.", "fr": "Impossible d’initialiser le compte.", "pt": "Não foi possível inicializar a conta."},
  "cloudReadyNotConnected": <String, String>{"en": "Cloud ready, but not connected yet", "it": "Cloud pronto, ma non ancora collegato", "es": "Nube lista, pero aún no conectada", "fr": "Cloud prêt, mais pas encore connecté", "pt": "Cloud pronta, mas ainda não ligada"},
  "cloudBuildNoCredentials": <String, String>{"en": "This build does not contain the project cloud credentials yet. The app keeps working fully offline and no data is lost.", "it": "Questa build non contiene ancora le credenziali del progetto cloud. L’app continua a funzionare completamente offline e nessun dato viene perso.", "es": "Esta compilación aún no contiene las credenciales del proyecto en la nube. La app sigue funcionando completamente sin conexión y no se pierde ningún dato.", "fr": "Cette build ne contient pas encore les identifiants du projet cloud. L’app continue de fonctionner entièrement hors ligne et aucune donnée n’est perdue.", "pt": "Esta build ainda não contém as credenciais do projeto cloud. A app continua a funcionar totalmente offline e nenhum dado é perdido."},
  "sharedPrepared": <String, String>{"en": "The sync structure and database are already prepared for the shared space too.", "it": "La struttura di sincronizzazione e il database sono già predisposti anche per lo spazio condiviso.", "es": "La estructura de sincronización y la base de datos ya están preparadas también para el espacio compartido.", "fr": "La structure de synchronisation et la base de données sont déjà prêtes aussi pour l’espace partagé.", "pt": "A estrutura de sincronização e a base de dados já estão preparadas também para o espaço partilhado."},
  "signInAccount": <String, String>{"en": "Sign in to your account", "it": "Accedi al tuo account", "es": "Inicia sesión en tu cuenta", "fr": "Connecte-toi à ton compte", "pt": "Inicia sessão na tua conta"},
  "googlePrimary": <String, String>{"en": "Google is the main sign-in for Anna's Diary. Email/password sign-in remains available for existing accounts.", "it": "Google è l’accesso principale di Anna's Diary. Il login email/password resta disponibile per gli account esistenti.", "es": "Google es el acceso principal de Anna's Diary. El inicio con email/contraseña sigue disponible para cuentas existentes.", "fr": "Google est la connexion principale d’Anna's Diary. La connexion e-mail/mot de passe reste disponible pour les comptes existants.", "pt": "Google é o acesso principal do Anna's Diary. O login email/palavra-passe continua disponível para contas existentes."},
  "existingEmailAccount": <String, String>{"en": "Existing email account", "it": "Account email esistente", "es": "Cuenta de email existente", "fr": "Compte e-mail existant", "pt": "Conta de email existente"},
  "myAccount": <String, String>{"en": "My account", "it": "Il mio account", "es": "Mi cuenta", "fr": "Mon compte", "pt": "A minha conta"},
  "lastSync": <String, String>{"en": "Last sync: {value}", "it": "Ultimo sync: {value}", "es": "Última sincronización: {value}", "fr": "Dernière synchronisation : {value}", "pt": "Última sincronização: {value}"},
  "dataZone": <String, String>{"en": "Data zone", "it": "Zona dati", "es": "Zona de datos", "fr": "Zone de données", "pt": "Zona de dados"},
  "deletePermanentNote": <String, String>{"en": "Account deletion is permanent and requires explicit confirmation.", "it": "L’eliminazione dell’account è permanente e richiede una conferma esplicita.", "es": "La eliminación de la cuenta es permanente y requiere confirmación explícita.", "fr": "La suppression du compte est définitive et exige une confirmation explicite.", "pt": "A eliminação da conta é permanente e exige confirmação explícita."},
  "howItWorks": <String, String>{"en": "How it works", "it": "Come funziona", "es": "Cómo funciona", "fr": "Comment ça marche", "pt": "Como funciona"},
  "localFirstHow": <String, String>{"en": "• The app always saves on the device first.\n• Changes are queued even without Internet.\n• When cloud is available again, only changed items are synced.\n• Private agenda and Noi ♡ remain separate archives.", "it": "• L’app salva sempre prima sul dispositivo.\n• Le modifiche vengono messe in coda anche senza Internet.\n• Quando il cloud torna disponibile, vengono sincronizzati solo gli elementi cambiati.\n• Agenda privata e Noi ♡ restano archivi separati.", "es": "• La app siempre guarda primero en el dispositivo.\n• Los cambios se ponen en cola incluso sin Internet.\n• Cuando vuelve la nube, solo se sincronizan los elementos modificados.\n• La agenda privada y Noi ♡ siguen siendo archivos separados.", "fr": "• L’app enregistre toujours d’abord sur l’appareil.\n• Les modifications sont mises en file même sans Internet.\n• Quand le cloud revient, seuls les éléments modifiés sont synchronisés.\n• L’agenda privé et Noi ♡ restent des archives séparées.", "pt": "• A app guarda sempre primeiro no dispositivo.\n• As alterações ficam em fila mesmo sem Internet.\n• Quando a cloud regressa, apenas os elementos alterados são sincronizados.\n• A agenda privada e Noi ♡ continuam arquivos separados."},
  "privateDefaultCloud": <String, String>{"en": "Private remains the default. Noi ♡ items are shared only when you explicitly choose it.", "it": "Privato resta l’impostazione predefinita. Gli elementi Noi ♡ sono condivisi solo quando lo scegli esplicitamente.", "es": "Privado sigue siendo la opción predeterminada. Los elementos Noi ♡ solo se comparten cuando lo eliges explícitamente.", "fr": "Privé reste le choix par défaut. Les éléments Noi ♡ ne sont partagés que lorsque tu le choisis explicitement.", "pt": "Privado continua a ser a predefinição. Os elementos Noi ♡ só são partilhados quando o escolhes explicitamente."},
  "accountDeleted": <String, String>{"en": "Account and data permanently deleted.", "it": "Account e dati eliminati definitivamente.", "es": "Cuenta y datos eliminados definitivamente.", "fr": "Compte et données supprimés définitivement.", "pt": "Conta e dados eliminados permanentemente."},
  "accountSignedOut": <String, String>{"en": "Account disconnected. Its data remains stored on the device but is no longer shown.", "it": "Account disconnesso. I dati dell’account restano salvati sul dispositivo ma non sono più mostrati.", "es": "Cuenta desconectada. Sus datos siguen guardados en el dispositivo pero ya no se muestran.", "fr": "Compte déconnecté. Ses données restent enregistrées sur l’appareil mais ne sont plus affichées.", "pt": "Conta desligada. Os respetivos dados continuam guardados no dispositivo, mas já não são mostrados."},
  "pendingSafe": <String, String>{"en": "Local data is safe: {count} changes are waiting for the network.", "it": "I dati locali sono al sicuro: {count} modifiche restano in attesa di rete.", "es": "Los datos locales están seguros: {count} cambios esperan la red.", "fr": "Les données locales sont en sécurité : {count} modifications attendent le réseau.", "pt": "Os dados locais estão seguros: {count} alterações aguardam a rede."},
};

extension AnnaD3Strings on AnnaStrings {
  String d3(String key) {
    final entry = _d3Catalog[key];
    assert(entry != null, 'Missing D3 localization key: $key');
    final safe = entry ?? const <String, String>{};
    return safe[languageCode] ?? safe['en'] ?? key;
  }
  String d3Format(String key, Map<String, Object?> values) {
    var value = d3(key);
    for (final entry in values.entries) {
      value = value.replaceAll('{${entry.key}}', '${entry.value ?? ''}');
    }
    return value;
  }
}
