part of '../main.dart';

const Map<String, Map<String, String>> _d3Catalog = {
  "onboardingTitle": <String, String>{"en": "Your agenda, truly yours.", "it": "La tua agenda, davvero tua.", "es": "Tu agenda, de verdad tuya.", "fr": "Ton agenda, vraiment à toi.", "pt": "A tua agenda, verdadeiramente tua."},
  "onboardingDescription": <String, String>{"en": "Appointments, diary, habits, ideas and memories in one place. The app saves on your device first; connect an account only if you want sync and Noi ♡.", "it": "Appuntamenti, diario, abitudini, idee e ricordi in un unico posto. L’app salva prima sul dispositivo; collega un account solo se vuoi sincronizzazione e Noi ♡.", "es": "Citas, diario, hábitos, ideas y recuerdos en un solo lugar. La app guarda primero en el dispositivo; conecta una cuenta solo si quieres sincronización y Noi ♡.", "fr": "Rendez-vous, journal, habitudes, idées et souvenirs au même endroit. L’app enregistre d’abord sur l’appareil ; connecte un compte seulement si tu veux la synchronisation et Noi ♡.", "pt": "Compromissos, diário, hábitos, ideias e memórias num só lugar. A app guarda primeiro no dispositivo; liga uma conta apenas se quiseres sincronização e Noi ♡."},
  "quickCapture": <String, String>{"en": "Quick capture", "it": "Cattura veloce", "es": "Captura rápida", "fr": "Capture rapide", "pt": "Captura rápida"},
  "quickCaptureSubtitle": <String, String>{"en": "Add a thought or commitment in seconds.", "it": "Aggiungi un pensiero o un impegno in pochi secondi.", "es": "Añade una idea o un compromiso en segundos.", "fr": "Ajoute une pensée ou un engagement en quelques secondes.", "pt": "Adiciona um pensamento ou compromisso em segundos."},
  "personalDiary": <String, String>{"en": "Personal diary", "it": "Diario personale", "es": "Diario personal", "fr": "Journal personnel", "pt": "Diário pessoal"},
  "privateOrNoi": <String, String>{"en": "Private or Noi ♡", "it": "Privato o Noi ♡", "es": "Privado o Noi ♡", "fr": "Privé ou Noi ♡", "pt": "Privado ou Noi ♡"},
  "privateDefault": <String, String>{"en": "Private is always the default; share only what you explicitly choose.", "it": "Privato è sempre il default; condividi solo ciò che scegli esplicitamente.", "es": "Privado es siempre la opción predeterminada; comparte solo lo que elijas explícitamente.", "fr": "Privé reste toujours le choix par défaut ; partage uniquement ce que tu choisis explicitement.", "pt": "Privado é sempre a predefinição; partilha apenas o que escolheres explicitamente."},
  "optionalPrivacy": <String, String>{"en": "Optional privacy", "it": "Privacy opzionale", "es": "Privacidad opcional", "fr": "Confidentialité facultative", "pt": "Privacidade opcional"},
  "optionalPrivacySubtitle": <String, String>{"en": "PIN and biometrics if you want to protect the agenda.", "it": "PIN e biometria se vuoi proteggere l’agenda.", "es": "PIN y biometría si quieres proteger la agenda.", "fr": "PIN et biométrie si tu veux protéger l’agenda.", "pt": "PIN e biometria se quiseres proteger a agenda."},
  "start": <String, String>{"en": "Start", "it": "Inizia", "es": "Empezar", "fr": "Commencer", "pt": "Começar"},
  "passwordUpdated": <String, String>{"en": "Password updated. Your account is ready.", "it": "Password aggiornata. Il tuo account è pronto.", "es": "Contraseña actualizada. Tu cuenta está lista.", "fr": "Mot de passe mis à jour. Ton compte est prêt.", "pt": "Palavra-passe atualizada. A tua conta está pronta."},
  "chooseNewPassword": <String, String>{"en": "Choose a new password", "it": "Scegli una nuova password", "es": "Elige una nueva contraseña", "fr": "Choisis un nouveau mot de passe", "pt": "Escolhe uma nova palavra-passe"},
  "recoveryLinkValid": <String, String>{"en": "The recovery link is valid. Set a new password to complete account recovery.", "it": "Il link di recupero è valido. Imposta la nuova password per completare il recupero dell’account.", "es": "El enlace de recuperación es válido. Define una nueva contraseña para completar la recuperación de la cuenta.", "fr": "Le lien de récupération est valide. Définis un nouveau mot de passe pour terminer la récupération du compte.", "pt": "A ligação de recuperação é válida. Define uma nova palavra-passe para concluir a recuperação da conta."},
  "newPassword": <String, String>{"en": "New password", "it": "Nuova password", "es": "Nueva contraseña", "fr": "Nouveau mot de passe", "pt": "Nova palavra-passe"},
  "repeatPassword": <String, String>{"en": "Repeat password", "it": "Ripeti password", "es": "Repite la contraseña", "fr": "Répète le mot de passe", "pt": "Repete a palavra-passe"},
  "updatePassword": <String, String>{"en": "Update password", "it": "Aggiorna password", "es": "Actualizar contraseña", "fr": "Mettre à jour le mot de passe", "pt": "Atualizar palavra-passe"},
  "unlockAnna": <String, String>{"en": "Unlock Anna's Diary", "it": "Sblocca Anna's Diary", "es": "Desbloquear Anna's Diary", "fr": "Déverrouiller Anna's Diary", "pt": "Desbloquear Anna's Diary"},
  "incorrectPin": <String, String>{"en": "Incorrect PIN.", "it": "PIN non corretto.", "es": "PIN incorrecto.", "fr": "PIN incorrect.", "pt": "PIN incorreto."},
  "agendaLocked": <String, String>{"en": "Agenda locked", "it": "Agenda bloccata", "es": "Agenda bloqueada", "fr": "Agenda verrouillé", "pt": "Agenda bloqueada"},
  "unlock": <String, String>{"en": "Unlock", "it": "Sblocca", "es": "Desbloquear", "fr": "Déverrouiller", "pt": "Desbloquear"},
  "useBiometric": <String, String>{"en": "Use biometrics", "it": "Usa biometria", "es": "Usar biometría", "fr": "Utiliser la biométrie", "pt": "Usar biometria"},
  "retry": <String, String>{"en": "Retry", "it": "Riprova", "es": "Reintentar", "fr": "Réessayer", "pt": "Tentar novamente"},
  "identityIntro": <String, String>{"en": "One account for agenda, backup, sync and Noi ♡.", "it": "Un solo account per agenda, backup, sincronizzazione e Noi ♡.", "es": "Una sola cuenta para agenda, copia, sincronización y Noi ♡.", "fr": "Un seul compte pour agenda, sauvegarde, synchronisation et Noi ♡.", "pt": "Uma só conta para agenda, backup, sincronização e Noi ♡."},
  "haveEmailAccount": <String, String>{"en": "I already have an email/password account", "it": "Ho già un account email/password", "es": "Ya tengo una cuenta de email/contraseña", "fr": "J’ai déjà un compte e-mail/mot de passe", "pt": "Já tenho uma conta de email/palavra-passe"},
  "identityPrivacy": <String, String>{"en": "The account identifies only you. Private content stays separate from Noi ♡ and offline changes sync automatically when the network returns.", "it": "L’account identifica solo te. I contenuti privati restano separati da Noi ♡ e le modifiche offline vengono sincronizzate automaticamente quando torna la rete.", "es": "La cuenta solo te identifica a ti. El contenido privado permanece separado de Noi ♡ y los cambios sin conexión se sincronizan automáticamente cuando vuelve la red.", "fr": "Le compte ne sert qu’à t’identifier. Le contenu privé reste séparé de Noi ♡ et les modifications hors ligne se synchronisent automatiquement au retour du réseau.", "pt": "A conta identifica apenas a ti. Os conteúdos privados permanecem separados de Noi ♡ e as alterações offline sincronizam automaticamente quando a rede regressa."},
  "accountConnectedSyncPending": <String, String>{"en": "Account connected, sync still to complete", "it": "Account connesso, sincronizzazione da completare", "es": "Cuenta conectada, sincronización pendiente", "fr": "Compte connecté, synchronisation à terminer", "pt": "Conta ligada, sincronização por concluir"},
  "preparingSpace": <String, String>{"en": "Preparing your space…", "it": "Preparazione del tuo spazio…", "es": "Preparando tu espacio…", "fr": "Préparation de ton espace…", "pt": "A preparar o teu espaço…"},
  "cloudDisabled": <String, String>{"en": "Cloud not configured", "it": "Cloud non configurato", "es": "Nube no configurada", "fr": "Cloud non configuré", "pt": "Cloud não configurada"},
  "cloudConnecting": <String, String>{"en": "Connecting...", "it": "Connessione...", "es": "Conectando...", "fr": "Connexion...", "pt": "A ligar..."},
  "cloudSignedOut": <String, String>{"en": "Not connected", "it": "Non connesso", "es": "No conectado", "fr": "Non connecté", "pt": "Não ligado"},
  "cloudSyncing": <String, String>{"en": "Syncing...", "it": "Sincronizzazione...", "es": "Sincronizando...", "fr": "Synchronisation...", "pt": "A sincronizar..."},
  "cloudSyncError": <String, String>{"en": "Sync error", "it": "Errore di sincronizzazione", "es": "Error de sincronización", "fr": "Erreur de synchronisation", "pt": "Erro de sincronização"},
  "resetEmailSent": <String, String>{"en": "If the address is registered, you will receive an email to choose a new password.", "it": "Se l’indirizzo è registrato, riceverai una mail per scegliere una nuova password.", "es": "Si la dirección está registrada, recibirás un correo para elegir una nueva contraseña.", "fr": "Si l’adresse est enregistrée, tu recevras un e-mail pour choisir un nouveau mot de passe.", "pt": "Se o endereço estiver registado, receberás um email para escolher uma nova palavra-passe."},
  "agendaSynced": <String, String>{"en": "Agenda fully synced.", "it": "Agenda completamente sincronizzata.", "es": "Agenda completamente sincronizada.", "fr": "Agenda entièrement synchronisé.", "pt": "Agenda totalmente sincronizada."},
  "accountAndSync": <String, String>{"en": "Account and sync", "it": "Account e sincronizzazione", "es": "Cuenta y sincronización", "fr": "Compte et synchronisation", "pt": "Conta e sincronização"},
  "continueGoogle": <String, String>{"en": "Continue with Google", "it": "Continua con Google", "es": "Continuar con Google", "fr": "Continuer avec Google", "pt": "Continuar com Google"},
  "existingAccount": <String, String>{"en": "Sign in with an existing account", "it": "Accedi con account esistente", "es": "Iniciar sesión con una cuenta existente", "fr": "Se connecter avec un compte existant", "pt": "Iniciar sessão com uma conta existente"},
  "forgotPassword": <String, String>{"en": "Forgot password?", "it": "Password dimenticata?", "es": "¿Olvidaste la contraseña?", "fr": "Mot de passe oublié ?", "pt": "Esqueceste a palavra-passe?"},
  "noCompletedSync": <String, String>{"en": "No completed sync yet", "it": "Nessuna sincronizzazione completata", "es": "Aún no hay sincronizaciones completadas", "fr": "Aucune synchronisation terminée", "pt": "Ainda não há sincronizações concluídas"},
  "pendingChanges": <String, String>{"en": "Pending changes", "it": "Modifiche in attesa", "es": "Cambios pendientes", "fr": "Modifications en attente", "pt": "Alterações pendentes"},
  "syncNow": <String, String>{"en": "Sync now", "it": "Sincronizza ora", "es": "Sincronizar ahora", "fr": "Synchroniser maintenant", "pt": "Sincronizar agora"},
  "disconnectAccount": <String, String>{"en": "Disconnect account", "it": "Disconnetti account", "es": "Desconectar cuenta", "fr": "Déconnecter le compte", "pt": "Desligar conta"},
  "deleteAccountTitle": <String, String>{"en": "Permanently delete the account?", "it": "Eliminare definitivamente l’account?", "es": "¿Eliminar definitivamente la cuenta?", "fr": "Supprimer définitivement le compte ?", "pt": "Eliminar permanentemente a conta?"},
  "deleteAccountData": <String, String>{"en": "Delete account and data", "it": "Elimina account e dati", "es": "Eliminar cuenta y datos", "fr": "Supprimer le compte et les données", "pt": "Eliminar conta e dados"},
  "confirmation": <String, String>{"en": "Confirmation", "it": "Conferma", "es": "Confirmación", "fr": "Confirmation", "pt": "Confirmação"},
};

extension AnnaD3Strings on AnnaStrings {
  String d3(String key) {
    final entry = _d3Catalog[key];
    assert(entry != null, 'Missing D3 localization key: $key');
    final safe = entry ?? const <String, String>{};
    return safe[languageCode] ?? safe['en'] ?? key;
  }
}
